use_frameworks!

platform :ios, '9.0'

target 'YJAMRConverter_Example' do
  pod 'YJAMRConverter', :path => '../'
  pod 'Masonry'

  target 'YJAMRConverter_Tests' do
    inherit! :search_paths

    
  end
end
